zoom:
  api:
    base-url: https://api.zoom.us/v2
    account-id: *
    client-id: *
    client-secret: *
spring:
  security:
    jwt:
      secret: YourJWTSecretKeyShouldBeAtLeast512BitsLongForHS512Algorithm12345 # Your existing JWT secret
      expiration-ms: 86400000
  datasource:
    url: jdbc:mysql://localhost:3306/db_smartClass
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update